### ISSUE TITLE
兄弟，运行不了，缺少数据库文件，CleverBamboo.com这个域名一直报错

### ISSUE THREAD

**Issue by lankii** [CleverBamboo/bee-shop-b2c#1]
兄弟，运行不了，缺少数据库文件，CleverBamboo.com这个域名一直报错，qor感觉没你写的好

**Comment by CleverBamboo** [comment]
(⊙o⊙)…，我还在开发呢

**Comment by CleverBamboo** [comment]
CleverBamboo.com这个报错表现，你要在Go/src目录下创建这样的文件夹，并且把放到该文件夹下
