### ISSUE TITLE
你准备用api模式吗？

### ISSUE THREAD

**Issue by lankii** [CleverBamboo/bee-shop-b2c#2]
你准备用api模式吗？看过很多，基本上是用graphql，pwa架构

看遍全网,golang没有一个完整的商城项目。djiang有不少完成的但是性能没法比，冗余性太复杂，五花八门的前端架构，还有就是rails的有不少完整功能齐全的，但是不熟悉rail。我这年纪感觉重新从头开始写跟不上新技术，也没那个精力了，倒是很像用Julialang的，那个完全没有，包功能不完善。兄弟加油，如果能开发出一个，一定是星最多的，粉丝也会多

**Comment by CleverBamboo** [comment]
一直都是API模式呀，前端项目在我的另一个库里，叫做bee-shop-b2c-admin
